TVG.Admin/Controllers/ControlTagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NPoco;
using TVG.Data.Domain;
using TVG.Data.Services;
using TVG.Core.Logging;
using TVG.Admin.Models;
using TVG.Core.Helper;

namespace TVG.Admin.Controllers
{
    public class ControlTagController : BaseController
    {
        IControlTagService controlTagService;
        ILogManager logger;

        public ControlTagController(IControlTagService controlTagService, ILogManager logger)
        {
            this.controlTagService = controlTagService;
            this.logger = logger;
        }

        // GET: Tag
        public ActionResult Index()
        {
            Dictionary<string, object> args = new Dictionary<string, object>();
            var list = controlTagService.GetControlTags(args);
            return View(list);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ControlTagCreateModel model)
        {
            if (ModelState.IsValid)
            {
                ControlTag item = new ControlTag
                {
                    Name = model.Name,
                    Slug = model.Slug,
                    DisplayOrder = model.DisplayOrder,
                    Color = model.Color,
                    IsDeleted = false
                };
                var result = controlTagService.Insert(item);
                if (result > 0)
                {
                    TempData["message"] = "Tạo mới thành công";
                    TempData["status"] = "success";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            if (id <= 0) return RedirectToAction("Index");
            var item = controlTagService.GetById(id);
            if (item == null) return RedirectToAction("Index");
            var model = new ControlTagEditModel
            {
                Id = item.Id,
                Name = item.Name,
                Slug = item.Slug,
                DisplayOrder = item.DisplayOrder,
                Color = item.Color
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ControlTagEditModel model)
        {
            if (ModelState.IsValid)
            {
                var item = controlTagService.GetById(model.Id);
                item.Name = model.Name;
                item.Slug = model.Slug;
                item.DisplayOrder = model.DisplayOrder;
                item.Color = model.Color;
                var result = controlTagService.Update(item);
                if (result > 0)
                {
                    TempData["message"] = "Tạo mới thành công";
                    TempData["status"] = "success";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(FormCollection collection)
        {
            try
            {
                int id = ValueHelper.TryGet(collection["deletedId"], 0);
                if (id > 0)
                {
                    controlTagService.Delete(id);
                }
                TempData["message"] = "Xoá thành công";
                TempData["status"] = "success";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                TempData["message"] = "Lỗi: " + ex.Message;
                TempData["status"] = "error";
                logger.Error(ex);
                return RedirectToAction("Index");
            }
        }
    }
}

TVG.Admin/Views/ControlTag/Create.cshtml
@using TVG.Data
@model TVG.Admin.Models.ControlTagCreateModel

@{
    ViewBag.Title = "Tạo trạng thái văn bản mới";
}

@section ContentHeader{
    <h1>
        @ViewBag.Title
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/lawissuedplace"><i class="fa fa-dashboard"></i> Trạng thái văn bản</a></li>
        <li class="active">@ViewBag.Title</li>
    </ol>
}

@using (Html.BeginForm("Create", "ControlTag", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="glyphicon glyphicon-edit"></i> Thông tin trạng thái</h3>
        </div>
        <div class="box-body">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <div class="form-group">
                <label class="col-md-2 control-label">Tên trạng thái</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control required", placeholder = "Tên trạng thái" })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Tên SEO</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Slug, new { @class = "form-control required", placeholder = "Tên SEO" })
                    @Html.ValidationMessageFor(model => model.Slug)
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Màu sắc</label>
                <div class="col-md-10">
                    <div class="input-group color-picker">
                        <span class="input-group-addon">
                            <i></i>
                        </span>
                        @Html.TextBoxFor(model => model.Color, new { @class = "form-control ", placeholder = "Màu sắc" })
                        
                    </div>
                    
                    @Html.ValidationMessageFor(model => model.Color)
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Thứ tự</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.DisplayOrder, new { @type = "number", @class = "form-control", placeholder = "Thứ tự sắp xếp" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-primary" value="Lưu lại" />
                    @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    </div>
}
@section scripts{
    <link href="~/Scripts/plugins/colorpicker/css/bootstrap-colorpicker.min.css" rel="stylesheet" />
    <script src="~/Scripts/plugins/colorpicker/js/bootstrap-colorpicker.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            //tạo url rewrite theo tiêu đề
            $("#Name").blur(function () {
                var text = $(this).val();
                text = framework.Slugify(text);
                $("#Slug").val(text);
            });

            $(".color-picker").colorpicker({
                format: "hex",
                customClass: 'colorpicker-2x',
                sliders: {
                    saturation: {
                        maxLeft: 200,
                        maxTop: 200
                    },
                    hue: {
                        maxTop: 200
                    },
                    alpha: {
                        maxTop: 200
                    }
                }
            });
        });

    </script>
}

TVG.Admin/Views/ControlTag/Edit.cshtml
@using TVG.Data.Domain
@model TVG.Admin.Models.ControlTagEditModel

@{
    ViewBag.Title = "Sửa trạng thái văn bản";
}

@section ContentHeader{
    <h1>
        @ViewBag.Title
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/lawissuedplace"><i class="fa fa-dashboard"></i> Trạng thái văn bản</a></li>
        <li class="active">@ViewBag.Title</li>
    </ol>
}
@using (Html.BeginForm("Edit", "ControlTag", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="glyphicon glyphicon-edit"></i> Thông tin trạng thái</h3>
        </div>
        <div class="box-body">

            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.Id)
            <div class="form-group">
                <label class="col-md-2 control-label">Tên trạng thái</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control required", placeholder = "Tên trạng thái" })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Tên SEO</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Slug, new { @class = "form-control required", placeholder = "Tên SEO" })
                    @Html.ValidationMessageFor(model => model.Slug)
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Màu sắc</label>
                <div class="col-md-10">
                    <div class="input-group color-picker">
                        <span class="input-group-addon">
                            <i></i>
                        </span>
                        @Html.TextBoxFor(model => model.Color, new { @class = "form-control ", placeholder = "Màu sắc" })

                    </div>

                    @Html.ValidationMessageFor(model => model.Color)
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Thứ tự</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.DisplayOrder, new { @type = "number", @class = "form-control", placeholder = "Thứ tự sắp xếp" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-primary" value="Lưu lại" />
                    @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>

        </div>
    </div>
}
@section scripts{
    <link href="~/Scripts/plugins/colorpicker/css/bootstrap-colorpicker.min.css" rel="stylesheet" />
<script src="~/Scripts/plugins/colorpicker/js/bootstrap-colorpicker.min.js"></script>

<script type="text/javascript">
        $(document).ready(function () {
            //tạo url rewrite theo tiêu đề
            $("#Name").blur(function () {
                var text = $(this).val();
                text = framework.Slugify(text);
                $("#Slug").val(text);
            });

            $(".color-picker").colorpicker({
                format: "hex",
                customClass: 'colorpicker-2x',
                sliders: {
                    saturation: {
                        maxLeft: 200,
                        maxTop: 200
                    },
                    hue: {
                        maxTop: 200
                    },
                    alpha: {
                        maxTop: 200
                    }
                }
            });
        });

</script>
}

TVG.Admin/Views/ControlTag/Index.cshtml
@model List<TVG.Data.Domain.ControlTag>
@{
    ViewBag.Title = "Quản lý trạng thái văn bản";
}
@section ContentHeader{
    <h1>
        @ViewBag.Title
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">@ViewBag.Title</li>
    </ol>
}
<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title"><i class="fa fa-folder"></i> Trạng thái văn bản</h3>
        <div class="box-tools">
            @Html.ActionLink("Tạo mới", "Create", null, new { @class = "btn btn btn-sm btn-primary" })
        </div>
    </div>
    <div class="box-body">
        @using (Html.BeginForm("Delete", "ControlTag", FormMethod.Post, new { id = "form1" }))
        {
            <input type="hidden" name="deletedId" id="deletedId" value="" />
            //Bảng dữ liệu
            <table class="table table-hover table-data">
                <thead>
                    <tr class="table-header">
                        <th>Màu</th>
                        <th>Tên</th>
                        <th>Tên SEO</th>
                        <th width="10%">Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ControlTag item in Model)
                    {
                        <tr>
                            <td data-th="Màu">
                                <span class="label" style="background:@item.Color; width: 50px; height: 20px;display:block"></span>
                            </td>
                            <td data-th="Tên">
                                @Html.ActionLink(item.Name, "Edit", new { id = item.Id })
                            </td>
                            <td data-th="Đường dẫn tĩnh">
                                @item.Slug
                            </td>
                            <td data-th="Thao tác">
                                @Html.ActionLink("Sửa", "Edit", new { id = item.Id })
                                @Html.Raw("|") <a href="#" data-id="@item.Id" class="linkDelete">Xoá</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            @*//hiện thông báo (nếu có)*@
            @if (!string.IsNullOrEmpty(TempData.SafeGet("status"))){
                @Html.Raw("toastr['" + @TempData.SafeGet("status") + "']('" + @TempData.SafeGet("message") + "');")
            }

            $('.linkDelete').click(function (e) {
                e.preventDefault();
                var id = $(this).attr("data-id");
                $('#deletedId').val(id);
                confirm("Bạn có chắc muốn xoá?") ? $("#form1").submit() : false;
            });
        });
    </script>
}