TVG.Admin/Models/PostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TVG.Data.Domain;

namespace TVG.Admin.Models
{
    public class PostCreateModel
    {
        [Required(ErrorMessageResourceType = typeof(Localizations.Models), ErrorMessageResourceName = "Validation_Required")]
        [Display(ResourceType = typeof(Localizations.Models), Name = "Post_Title")]
        public string Title { get; set; }
        [Required(ErrorMessage = "URL tĩnh không được bỏ trống")]
        public string Slug { get; set; }
        [Required(ErrorMessage = "Tóm tắt không được bỏ trống")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Nội dung không được bỏ trống")]
        [AllowHtml]
        public string Content { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeyword { get; set; }
        public string Image { get; set; }
        public string PostType { get; set; }
    }

    public class PostEditModel
    {
        [Required]
        public int Id { get; set; }
        [Required(ErrorMessageResourceType = typeof(Localizations.Models), ErrorMessageResourceName = "Validation_Required")]
        [Display(ResourceType = typeof(Localizations.Models), Name = "Post_Title")]
        public string Title { get; set; }
        [Required(ErrorMessage = "URL tĩnh không được bỏ trống")]
        public string Slug { get; set; }
        [Required(ErrorMessage = "Tóm tắt không được bỏ trống")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Nội dung không được bỏ trống")]
        [AllowHtml]
        public string Content { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeyword { get; set; }
        public string Image { get; set; }
        public string PostType { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime PublishedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
    }

    public class PostFormModel
    {
        public PostFormModel()
        {
            this.Post = new Post();
        }
        public Post Post { get; set; }
        [Required]
        public int Id { get; set; }
        [Required(ErrorMessageResourceType = typeof(Localizations.Models), ErrorMessageResourceName = "Validation_Required")]
        [Display(ResourceType = typeof(Localizations.Models), Name = "Post_Title")]
        public string Title { get; set; }
        [Required(ErrorMessage = "URL tĩnh không được bỏ trống")]
        public string Slug { get; set; }
        [Required(ErrorMessage = "Tóm tắt không được bỏ trống")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Nội dung không được bỏ trống")]
        [AllowHtml]
        public string Content { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeyword { get; set; }
        public string Image { get; set; }
        public string PostType { get; set; }
        public int PostStatus { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime PublishedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
        public int PublishedBy { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        public string Note { get; set; }
        public int DisplayOrder { get; set; }

        public List<int> PostTermIds { get; set; }
        public List<TaxonomyTerm> Categories { get; set; }
        public List<PostMeta> PostMetas { get; set; }
        public List<PostTag> PostTags { get; set; }
        public PostExt PostExt { get; set; }

        public string FormAction { get; set; }
    }

    public class ForKidFormModel : PostFormModel
    {
        public List<TaxonomyTerm> Categories_chu_de { get; set; }
        public List<TaxonomyTerm> Categories_nguyen_lieu { get; set; }
        public List<TaxonomyTerm> Categories_linh_vuc { get; set; }
        public List<TaxonomyTerm> Categories_su_kien { get; set; }
    }

    public class ForTeacherFormModel : PostFormModel
    {
        public List<TaxonomyTerm> Categories_thong_tin_nganh { get; set; }
        public List<TaxonomyTerm> Categories_giao_an_mau { get; set; }
        public List<TaxonomyTerm> Categories_ke_hoach { get; set; }
    }

    public class ForMomFormModel : PostFormModel
    {
        public List<TaxonomyTerm> Categories_album { get; set; }
        public List<TaxonomyTerm> Categories_nguyen_lieu { get; set; }
    }
}

TVG.Admin/Controllers/PostController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using NPoco;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using TVG.Admin.Extensions;
using TVG.Admin.Models;
using TVG.Core.Helper;
using TVG.Core.Logging;
using TVG.Data;
using TVG.Data.Domain;
using TVG.Data.Services;
using TVG.Identity;

namespace TVG.Admin.Controllers
{
    public class PostController : BaseController
    {
        private const string ACTION_EDIT = "edit";
        private const string ACTION_CREATE = "create";
        private const string POST_TYPE = "post";

        private const string PERMISSION_VIEW = "cms_post_view";
        private const string PERMISSION_EDIT = "cms_post_edit";
        private const string PERMISSION_ADD = "cms_post_add";
        private const string PERMISSION_DELETE = "cms_post_delete";
        private const string PERMISSION_EDIT_OWN = "cms_post_edit_own";
        private const string PERMISSION_EDIT_RULES = "cms_post_edit, cms_post_edit_own";
        private const string PERMISSION_APPROVE = "cms_post_approve";
        private const string PERMISSION_REJECT = "cms_post_reject";

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        IPostService postService;
        ITaxonomyService taxonomyService;
        private readonly ILogManager logger;
        public PostController(
            IPostService postService, 
            ITaxonomyService taxonomyService,
            ILogManager logger,
            IPermissionService permissionService)
        {
            this.postService = postService;
            this.taxonomyService = taxonomyService;
            this.logger = logger;
            this.permissionService = permissionService;
        }

        [TVGAuthorizeAction(PermissionName = PERMISSION_VIEW)]
        public ActionResult Index()
        {
            Dictionary<string, object> args = new Dictionary<string, object>();
            args["postType"] = ValueHelper.TryGet(Request.QueryString["type"], "post");
            args["termId"] = ValueHelper.TryGet(Request.QueryString["catId"], 0);
            args["keyword"] = ValueHelper.TryGet(Request.QueryString["kw"], "");
            args["status"] = ValueHelper.TryGet(Request.QueryString["status"], -1);
            args["userId"] = ValueHelper.TryGet(Request.QueryString["userId"], 0);
            args["pageIndex"] = ValueHelper.TryGet(Request.QueryString["pId"], 1);
            args["pageSize"] = ValueHelper.TryGet(Request.QueryString["pSize"], 20);
            args["isDeleted"] = ValueHelper.TryGet(Request.QueryString["deleted"], false);

            var posts = postService.GetPosts(args);

            for (int i = 0; i < posts.Items.Count; i++)
            {
                posts.Items[i].Terms = postService.GetPostTermsByPostId(posts.Items[i].Id);
            }

            //Lấy danh sách category
            Dictionary<string, object> argsCat = new Dictionary<string, object>();
            argsCat["type"] = "category";
            argsCat["getTree"] = true;
            Page<TaxonomyTerm> terms = taxonomyService.GetTerms(argsCat);
            ViewBag.Categories = terms;

            //lấy danh sách user
            ViewBag.Users = UserManager.Users.ToList();

            ViewBag.PostStatuses = ConstantDatas.PostStatus;

            ViewBag.FilterCategoryId = ValueHelper.TryGet(Request.QueryString["catId"], 0);
            ViewBag.FilterPostType = ValueHelper.TryGet(Request.QueryString["type"], 0);
            ViewBag.FilterKeyword = ValueHelper.TryGet(Request.QueryString["kw"], "");
            ViewBag.FilterUserId = ValueHelper.TryGet(Request.QueryString["userId"], 0);
            ViewBag.FilterStatus = Request.QueryString["status"].TryConvert<int>(-1);
            ViewBag.FilterDeleted = Request.QueryString["deleted"].TryConvert<bool>(false);

            Dictionary<string, bool> permissions = HasPermissions(new List<string>{ PERMISSION_ADD, PERMISSION_DELETE, PERMISSION_EDIT });
            ViewBag.CanInsert = permissions[PERMISSION_ADD];
            ViewBag.CanEdit = permissions[PERMISSION_EDIT];
            ViewBag.CanDelete = permissions[PERMISSION_DELETE];

            return View(posts);
        }

        [TVGAuthorizeAction(PermissionName = PERMISSION_ADD)]
        public ActionResult Create()
        {
            var model = new PostFormModel();
            PrepareFormModel(model);
            return View("Form", model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [TVGAuthorizeAction(PermissionName = PERMISSION_ADD)]
        public ActionResult Create(PostFormModel model, params int[] category)
        {
            if (ModelState.IsValid)
            {
                var dataPost = PrepareSaveModel(model, null);
                var result = postService.InsertPost(dataPost);

                if (result > 0)
                {
                    TempData["message"] = "Tạo mới thành công";
                    TempData["status"] = "success";
                    return RedirectToAction("Index");
                }
            }

            PrepareFormModel(model);
            return View("Form", model);
        }

        [TVGAuthorizeAction(PermissionName = PERMISSION_EDIT_RULES)]
        public ActionResult Edit(int id)
        {
            if (id <= 0) return RedirectToAction("Index");
            Post post = postService.GetPostById(id);
            if (post == null) return RedirectToAction("Index");

            //tạo view model
            PostFormModel model = new PostFormModel();
            PrepareFormModel(model, post, ACTION_EDIT);

            return View("Form", model);
        }

        //POST: Post/Edit/
        [HttpPost]
        [ValidateAntiForgeryToken]
        [TVGAuthorizeAction(PermissionName = PERMISSION_EDIT_RULES)]
        [HttpParamAction("Edit")]
        public ActionResult Save(PostFormModel model, params int[] category)
        {
            if (ModelState.IsValid)
            {
                var status = model.PostStatus;
                if (status == PostStatus.GetPostStatusIdByCode(PostStatus.BI_TRA_VE))
                {
                    status = PostStatus.GetPostStatusIdByCode(PostStatus.CHO_DUYET);
                }
                var result = SavePost(model, status);

                if (result > 0)
                {
                    TempData["message"] = "Cập nhật thành công";
                    TempData["status"] = "success";
                    return RedirectToAction("Edit", new { id = model.Id });
                }
            }

            PrepareFormModel(model, null, ACTION_EDIT);
            return View("Form", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [TVGAuthorizeAction(PermissionName = PERMISSION_EDIT_RULES)]
        [HttpParamAction("Edit")]
        public ActionResult Approve(PostFormModel model, params int[] category)
        {
            if (ModelState.IsValid)
            {
                var status = PostStatus.GetPostStatusIdByCode(PostStatus.DA_DUYET);
                var result = SavePost(model, status);

                if (result > 0)
                {
                    TempData["message"] = "Cập nhật thành công";
                    TempData["status"] = "success";
                    return RedirectToAction("Edit", new { id = model.Id });
                }
            }

            PrepareFormModel(model, null, ACTION_EDIT);
            return View("Form", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [TVGAuthorizeAction(PermissionName = PERMISSION_EDIT_RULES)]
        [HttpParamAction("Edit")]
        public ActionResult Reject(PostFormModel model, params int[] category)
        {
            if (ModelState.IsValid)
            {
                var status = PostStatus.GetPostStatusIdByCode(PostStatus.BI_TRA_VE);
                var result = SavePost(model, status);

                if (result > 0)
                {
                    TempData["message"] = "Cập nhật thành công";
                    TempData["status"] = "success";
                    return RedirectToAction("Edit", new { id = model.Id });
                }
            }

            PrepareFormModel(model, null, ACTION_EDIT);
            return View("Form", model);
        }

        private int SavePost(PostFormModel model, int statusId)
        {
            var result = 0;
            var post = postService.GetPostById(model.Id);

            //chỉ thực hiện nếu bài viết có tồn tại và chưa bị xoá (IsDeleted=false)
            if (post != null && !post.IsDeleted)
            {
                var dataPost = PrepareSaveModel(model, post);
                dataPost.Post.PostStatus = statusId;
                result = postService.UpdatePost(dataPost);
            }
            return result;
        }

        //POST: Post/Delete
        [HttpPost]
        [TVGAuthorizeAction(PermissionName = PERMISSION_DELETE)]
        public ActionResult Delete(FormCollection collection)
        {
            try
            {
                int id = ValueHelper.TryGet(collection["deletedId"], 0);
                if (id > 0)
                {
                    postService.DeletePost(id);
                }
                TempData["message"] = "Xoá thành công";
                TempData["status"] = "success";
                var queryStrings = MyUrlHelper.QueryStringToDictionary(Request.Url.Query);
                return RedirectToAction("Index", new RouteValueDictionary(queryStrings));
            }
            catch(Exception ex)
            {

TVG.Admin/Views/Post/Create.cshtml
@model TVG.Admin.Models.PostCreateModel
@{
    ViewBag.Title = "Tạo bài viết mới";
}
@section ContentHeader{
    <h1>
        @ViewBag.Title
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/post"><i class="fa fa-dashboard"></i> Danh sách bài viết</a></li>
        <li class="active">@ViewBag.Title</li>
    </ol>
}
@using (Html.BeginForm("Create", "Post", FormMethod.Post, new { @class = "", role = "form" }))
{
    <div class="row">
        <div class="col-md-9">
            <div class="box form-horizontal">
                <div class="box-header with-border">
                    <h3 class="box-title"><i class="fa fa-newspaper-o"></i> Bài viết</h3>
                </div>
                <div class="box-body">
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)

                    <div class="form-group">
                        <label class="col-md-2 control-label">Tiêu đề (*)</label>
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Title, new { @class = "form-control", placeholder = "Tiêu đề bài viết" })
                            @Html.ValidationMessageFor(model => model.Title)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label">URL tĩnh (*)</label>
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Slug, new { @class = "form-control", placeholder = "URL tĩnh (vd: tieu-de-bai-viet)" })
                            @Html.ValidationMessageFor(model => model.Slug)
                            <div id="slug-length" class="seo-meta-length">0</div> ký tự. Tối đa 160 ký tự.
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label">Tóm tắt (*)</label>
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", placeholder = "Tóm tắt" })
                            @Html.ValidationMessageFor(model => model.Description)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2">Nội dung (*)</label>
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Content, new { id = "content", @class = "form-control", placeholder = "Nội dung" })
                            @Html.ValidationMessageFor(model => model.Content)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label">Meta Description</label>
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.MetaDescription, new { @class = "form-control", placeholder = "Meta description" })
                            @Html.ValidationMessageFor(model => model.MetaDescription)
                            <div id="meta-description-length" class="seo-meta-length">0</div> ký tự. Hầu hết các công cụ tìm kiếm sử dụng tối đa 160 ký tự cho miêu tả.
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label">Meta Keyword</label>
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.MetaKeyword, new { @class = "form-control", placeholder = "Meta keyword" })
                            @Html.ValidationMessageFor(model => model.MetaKeyword)
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"><i class="fa fa-newspaper-o"></i> Xuất bản</h3>
                </div>
                <div class="box-body">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" class="btn btn-primary" value="Lưu lại" />
                            @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-default" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"><i class="fa fa-newspaper-o"></i> Phân loại</h3>
                </div>
                <div class="box-body">
                    <div class="tabs" id="tabs">
                        <ul class="tabs-nav">
                            <li class="active"><a href="#tabCategory">Chuyên mục</a></li>
                        </ul>
                        <div class="tabs-content">
                            <div id="tabCategory" data-title="Chuyên mục" class="tab-panel active">
                                <ul class="checklist-terms">
                                    @foreach (TVG.Data.Domain.TaxonomyTerm item in ViewBag.TermTree.Items)
                                    {
                                        <li><input type="checkbox" name="category" value="@item.Id" /> @item.Name.AppendLeft('-', item.Level * 4)</li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"><i class="fa fa-paperclip"></i> Tag</h3>
                </div>
                <div class="box-body">
                    <div class="form-group">
                        <label>Chọn tag</label>
                        <select class="select2 form-control" name="tagIds" id="tagIds" multiple></select>
                    </div>
                    <div class="form-group">
                        <a href="#" id="link-add-tag">Không có tag, thêm tag mới?</a>
                        <div id="form-add-tag" class="input-group" style="display:none">
                            <input type="text" name="txtTagName" id="txtTagName" class="form-control" placeholder="Tên tag" />
                            <span class="input-group-btn">
                                <button class="btn btn-primary" id="button-add-tag">Thêm</button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"><i class="fa fa-newspaper-o"></i> Hình đại diện</h3>
                </div>
                <div class="box-body">
                    <div class="form-group text-center">
                        <div class="">
                            <div class="post-thumbnail">
                                <img id="post_image" class="" src="~/Content/images/noimage.png" />
                                <input type="hidden" id="image" name="Image" class="form-control" />
                            </div>
                            <button class="btn btn-primary btn-flat" id="image-select" type="button">Chọn</button>
                            <button class="btn btn-default btn-flat" id="image-remove" type="button">Xoá</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section scripts {
    <script src="~/Scripts/plugins/ckeditor/ckeditor.js"></script>
    <script>
        var puMedia;
        var arrTags = [];
        $(document).ready(function () {
            //ckeditor
            CKEDITOR.replace("content", {});

            @*tạo tab cho box phân loại*@
            $(".tabs").responsiveTab();

            @*tạo iCheck cho checkbox*@
            $('input[type="checkbox"], input[type="radio"]').iCheck({
                checkboxClass: 'icheckbox_minimal-blue',
                radioClass: 'iradio_minimal-blue',
            });

            $.ajax({
                url: "/Tag/GetTags",
                dataType: 'json',
                success: function (data) {
                    arrTags = [];
                    if (data.list.length > 0) {
                        for (var i = 0; i < data.list.length; i++) {
                            arrTags.push({ id: data.list[i].Id, text: data.list[i].Name });
                        }
                    }
                    $('#tagIds').select2({ data: arrTags, placeholder: "Chọn tag" });
                    return arrTags;
                },
            });

            $('#link-add-tag').click(function (e) {
                e.preventDefault();
                $("#form-add-tag").toggle();
            });
            $('#button-add-tag').click(function (e) {
                e.preventDefault();
                var text = $('#txtTagName').val();
                if (text.trim().length > 0) {
                    $.post("/Tag/AddTag", { tag: text }, function (data) {
                        if (data.status == "success") {
                            // Create the DOM option that is pre-selected by default
                            var newItem = new Option(text, data.tagId, true, true);
                            // Append it to the select
                            $("#tagIds").append(newItem).trigger('change');
                            $('#txtTagName').val('');
                        }
                    });
                }
            });

            @*nhấn chọn hình ảnh*@
            $('#image-select').click(function () {
                if (typeof (puMedia) == 'undefined' || puMedia.closed) {
                    puMedia = $.popupWindow("/mediamanager/?target=post_image", {
                        height: 490,
                        width: 950,
                        center: 'screen',
                        onFileSelected: processFile
                    });
                } else {
                    puMedia.focus();
                }
            });

            @*//button remove image*@
            $('#image-remove').click(function () {
                $('#post_image').attr('src', "/content/images/noimage.png");
                $('#image').val('');
            });

            @*//tạo url rewrite theo tiêu đề*@
            $("#Title").blur(function () {
                var text = $(this).val();
                $("#Description").val(text);
                $("#MetaDescription").val(text);
                $("#meta-description-length").text(text.length);
                text = framework.Slugify(text);
                if (text.length > 160) {
                    text = text.substr(0, 160);
                }
                $("#slug-length").text(text.length);
                $("#Slug").val(text);
            });
            $("#MetaDescription").blur(function () {
                var text = $(this).val();
                var sibling = $(this).siblings(".seo-meta-length");
                sibling.removeClass("error").text(text.length);
                if (text.length > 160) {
                    sibling.addClass("error");
                }
            });
        });

        @*xử lý sau khi chọn hình ảnh đại diện*@
        function processFile(e, files, target) {
            console.log(target);
            console.log(files);
            var fileUrl = files[0].url;
            var filePath = files[0].path;
            $('#' + target).attr('src', files[0].url);
            $('#image').val(filePath);
            puMedia.close();
        }
    </script>
}