TVG.Admin/Controllers/PermissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TVG.Core.Logging;
using TVG.Data.Domain;
using TVG.Data.Services;
using TVG.Identity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using TVG.Core.Helper;
using TVG.Admin.Extensions;

namespace TVG.Admin.Controllers
{
    public class PermissionController : BaseController
    {
        ILogManager logger;

        const string PERMISSION = "permission_edit";

        public PermissionController(ILogManager logger, IPermissionService permissionService)
        {
            this.logger = logger;
            this.permissionService = permissionService;
        }

        [TVGAuthorizeAction(PermissionName = PERMISSION)]
        public ActionResult Index()
        {
            //get all permission
            Dictionary<string, object> args = new Dictionary<string, object>();
            ViewBag.Permissions = permissionService.GetPermissions(args).Items;

            //get all roles
            var roleManager = HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            ViewBag.Roles = roleManager.Roles.ToList();

            //get all permission roles
            ViewBag.PermissionRoles = permissionService.GetRolePemissions(0);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [TVGAuthorizeAction(PermissionName = PERMISSION)]
        public ActionResult Index(FormCollection form)
        {
            List<string> selected = Request.Form.GetValues("permission_role").ConvertToList<string>();
            List<PermissionRole> permissionRoles = new List<PermissionRole>();
            string[] permission_role;
            foreach(var s in selected)
            {
                permission_role = s.Split('_');
                permissionRoles.Add(new PermissionRole {
                    PermissionId = permission_role[0].TryConvert<int>(0),
                    RoleId = permission_role[1].TryConvert<int>(0)
                });
            }
            permissionService.SavePermissionRoles(permissionRoles);
            return RedirectToAction("Index");
        }
        
    }
}

TVG.Admin/Views/Permission/Index.cshtml
@using TVG.Identity;
@{
    ViewBag.Title = "Quản lý phân quyền";
    List<Permission> permissions = ViewBag.Permissions as List<Permission>;
    List<PermissionRole> permissionRoles = ViewBag.PermissionRoles as List<PermissionRole>;
    List<ApplicationRole> roles = ViewBag.Roles as List<ApplicationRole>;
}
@section ContentHeader{
    <h1>
        @ViewBag.Title
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">@ViewBag.Title</li>
    </ol>
}
<div class="box">
@using (Html.BeginForm("Index", "Permission", FormMethod.Post, new { id = "form1" }))
{
    @Html.AntiForgeryToken()
    <div class="box-header">
        <h3 class="box-title">Danh sách phân quyền</h3>
    </div>
    <div class="box-body">
        <table class="table table-bordered table-hover table-data" id="table-permissions">
            <thead>
                <tr class="table-header">
                    <th>Nhóm</th>
                    <th data-orderable="false">Quyền hạn</th>
                    @foreach (var role in roles)
                    {
                        <th class="text-center" data-orderable="false">@role.Name</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var p in permissions)
                {
                    <tr>
                        <td>@p.CategoryName</td>
                        <td>@p.Name</td>
                        @foreach (var role in roles)
                        {
                            <td class="text-center">
                                @if (permissionRoles.Any(x => x.PermissionId == p.Id && x.RoleId == role.Id))
                                {
                                    <input type="checkbox" class="icheck" checked name="permission_role" value="@(p.Id)_@(role.Id)" />
                                }
                                else
                                {
                                    <input type="checkbox" class="icheck"  name="permission_role" value="@(p.Id)_@(role.Id)" />
                                }
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
            
    </div>
    <div class="box-footer">
        <button type="submit" name="submit" id="submit" class="btn btn-primary">Cập nhật</button>
    </div>
}
</div>

@section scripts {
    <link rel="stylesheet" href="~/Scripts/plugins/datatables/dataTables.bootstrap.css" />
    <script src="~/Scripts/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script>
        
        CMS.Common.bindiCheck();

        $('#table-permissions').each(function () {
            var Column_number_to_Merge = 1;

            // Previous_TD holds the first instance of same td. Initially first TD=null.
            var Previous_TD = null;
            var i = 1;
            $("tbody", this).find('tr').each(function () {
                // find the correct td of the correct column
                // we are considering the table column 1, You can apply on any table column
                var Current_td = $(this).find('td:nth-child(' + Column_number_to_Merge + ')');

                if (Previous_TD == null) {
                    // for first row
                    Previous_TD = Current_td;
                    i = 1;
                }
                else if (Current_td.text() == Previous_TD.text()) {
                    // the current td is identical to the previous row td
                    // remove the current td
                    Current_td.remove();
                    // increment the rowspan attribute of the first row td instance
                    Previous_TD.attr('rowspan', i + 1);
                    i = i + 1;
                }
                else {
                    // means new value found in current td. So initialize counter variable i
                    Previous_TD = Current_td;
                    i = 1;
                }
            });
        });

        CMS.Common.stickyTableHeader('#table-permissions');

    </script>
}