TVG.WebClient/Models/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TVG.WebClient.Models
{
    public class ContactViewModel
    {
        public int UserId { get; set; }
        public string ContactType { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập họ tên")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập email")]
        public string Email { get; set; }
        public string Phone { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tiêu đề")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập nội dung")]
        [AllowHtml]
        public string Message { get; set; }
    }

    public class ContactDocumentPostModel : ContactViewModel
    {
        [AllowHtml]
        public new string Message { get; set; }
        public string Author { get; set; }
        public string Journal { get; set; }
        public string Year { get; set; }
        public HttpPostedFileBase Attachment { get; set; }
    }
}

TVG.WebClient/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TVG.Data.Domain;
using TVG.Data.Services;
using TVG.Core.Helper;
using System.Text;
using Microsoft.AspNet.Identity;
using TVG.WebClient.Models;
using TVG.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.IO;

namespace TVG.WebClient.Controllers
{
    public class ContactController : BaseController
    {
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        IContactMessageService contactMessageService;
        ITaxonomyService taxonomyService;
        public ContactController(
            IContactMessageService contactMessageService,
            ITaxonomyService taxonomyService
        )
        {
            this.contactMessageService = contactMessageService;
            this.taxonomyService = taxonomyService;
        }

        public ActionResult SendQuestion()
        {
            return View();
        }

        [Route("contact/gui-bai-viet-hoc-thuat")]
        public ActionResult SendDocumentPost()
        {
            var model = new ContactDocumentPostModel();
            model.UserId = User.Identity.GetUserId().TryConvert<int>(0);
            ApplicationUser currentUser = UserManager.FindById(model.UserId);
            if (currentUser != null)
            {
                model.Email = currentUser.Email;
                model.Name = currentUser.LastName + " " + currentUser.FirstName;
                model.Phone = currentUser.PhoneNumber;
            }
            return View(model);
        }

        [Route("contact/gui-bai-viet-hoc-thuat")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult SendDocumentPost(ContactDocumentPostModel model)
        {
            //return View(model);
            var validTypes = new string[]
            {
                "application/pdf"
            };

            if (model.Attachment != null && model.Attachment.ContentLength > 0)
            {
                if (!validTypes.Contains(model.Attachment.ContentType))
                {
                    ModelState.AddModelError("Attachment", "File đính kèm không hợp lệ, vui lòng chọn file PDF");
                }
            }
            if (ModelState.IsValid)
            {
                var contact = new ContactMessage
                {
                    UserId = model.UserId,
                    ContactName = model.Name,
                    ContactEmail = model.Email,
                    ContactPhone = model.Phone,
                    Subject = model.Subject,
                    Message = model.Message,
                    CreatedDate = DateTime.Now
                };
                var attachmentUrl = "";
                if (model.Attachment != null && model.Attachment.ContentLength > 0)
                {
                    var uploadFolder = "~/uploads";
                    var uploadPath = "users";                    
                    var today = DateTime.Today;
                    uploadPath = Path.Combine(uploadPath, today.Year.ToString(), today.Month.ToString("00"));
                    if(model.UserId > 0)
                    {
                        uploadPath = Path.Combine(uploadPath, model.UserId.ToString());
                    }
                    var uploadDir = Server.MapPath(Path.Combine(uploadFolder, uploadPath));
                    if(!Directory.Exists(uploadDir))
                    {
                        Directory.CreateDirectory(uploadDir);
                    }
                    var filePath = Path.Combine(uploadDir, model.Attachment.FileName);
                    var fileUrl = Path.Combine(uploadPath, model.Attachment.FileName);
                    model.Attachment.SaveAs(filePath);
                    attachmentUrl = fileUrl.Replace("\\", "/");
                }

                var term = taxonomyService.GetTermBySlug(model.ContactType);
                List<int> termIds = new List<int>();
                if (term != null)
                {
                    termIds.Add(term.Id);
                }

                var meta = new List<ContactMessageMeta>();
                if (!string.IsNullOrEmpty(attachmentUrl))
                {
                    meta.Add(new ContactMessageMeta { ContactMessageId = contact.Id, MetaName = "attachment", MetaValue = attachmentUrl });
                }
                if(!string.IsNullOrEmpty(model.Author))
                {
                    meta.Add(new ContactMessageMeta { ContactMessageId = contact.Id, MetaName = "author", MetaValue = model.Author });
                }
                if (!string.IsNullOrEmpty(model.Journal))
                {
                    meta.Add(new ContactMessageMeta { ContactMessageId = contact.Id, MetaName = "journal", MetaValue = model.Journal });
                }
                if (!string.IsNullOrEmpty(model.Year))
                {
                    meta.Add(new ContactMessageMeta { ContactMessageId = contact.Id, MetaName = "published_year", MetaValue = model.Year });
                }

                var saveModel = new ContactMessageSaveModel();
                saveModel.Message = contact;
                saveModel.Metas = meta;
                saveModel.TermIds = termIds;
                int result = contactMessageService.InsertMessage(saveModel);
                if (result > 0)
                {
                    TempData["message"] = "Gửi thành công";
                    TempData["status"] = "success";
                }
            }

            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SendQuestion(string type, string name, string email, string phone, string subject, string message)
        {
            string status = "error";
            if (!string.IsNullOrEmpty(name) &&
                !string.IsNullOrEmpty(email) &&
                !string.IsNullOrEmpty(phone) &&
                !string.IsNullOrEmpty(subject) &&
                !string.IsNullOrEmpty(message))
            {
                var messageBody = "<p style='white-space: pre-line'>" + message + "</p>";
                var contact = new ContactMessage
                {
                    ContactName = name,
                    ContactEmail = email,
                    ContactPhone = phone,
                    Subject = subject,
                    Message = messageBody,
                    CreatedDate = DateTime.Now
                };
                var term = taxonomyService.GetTermBySlug("contact_type",type);
                List<int> termIds = new List<int>();
                if (term != null)
                {
                    termIds.Add(term.Id);
                }
                var model = new ContactMessageSaveModel();
                model.Message = contact;
                model.TermIds = termIds;

                int result = contactMessageService.InsertMessage(model);
                if (result > 0)
                {
                    status = "success";
                }
            }
            return Json(new { status = status });
        }

        [HttpPost]
        [ValidateInput(false)]
        public JsonResult SendDocumentPostAjax(string type, string name, string email, string phone, string subject, string message, string author, string journal, string year)
        {
            string status = "error";
            if (!string.IsNullOrEmpty(name) &&
                !string.IsNullOrEmpty(email) &&
                !string.IsNullOrEmpty(phone) &&
                !string.IsNullOrEmpty(subject) &&
                !string.IsNullOrEmpty(message))
            {
                var messageBody = new StringBuilder("");
                messageBody.Append("<p>Tác giả: " + author + "</p>");
                messageBody.Append("<p>Nơi đăng: " + journal + "</p>");
                messageBody.Append("<p>Năm đăng: " + year + "</p>");
                messageBody.Append("<p>Nội dung:</p>");
                messageBody.Append(message);
                var contact = new ContactMessage
                {
                    ContactName = name,
                    ContactEmail = email,
                    ContactPhone = phone,
                    Subject = subject,
                    Message = messageBody.ToString(),
                    CreatedDate = DateTime.Now
                };
                var term = taxonomyService.GetTermBySlug(type);
                List<int> termIds = new List<int>();
                if (term != null)
                {
                    termIds.Add(term.Id);
                }
                var model = new ContactMessageSaveModel();
                model.Message = contact;
                model.TermIds = termIds;

                int result = contactMessageService.InsertMessage(model);
                if (result > 0)
                {
                    status = "success";
                }
            }
            return Json(new { status = status });
        }
    }
}

TVG.WebClient/Views/Contact/SendDocumentPost.cshtml
@model ContactDocumentPostModel
@{
    ViewBag.Title = "TheGioiLuat.vn - Gửi bài viết";

    var breadcrumb = new List<BreadcrumbViewModel>();
    breadcrumb.Add(new BreadcrumbViewModel { Text = "Gửi yêu cầu" });
}
@Html.Partial("Breadcrumb", breadcrumb)
<div class="row">
    <article class="col-md-19">
        <header>
            <h1>Đóng góp bài viết học thuật</h1>
        </header>
        <section>
            @if(!TVGUserHelper.IsLoggedIn())
            {
                <div class=" alert alert-info">Vui lòng đăng nhập để gửi bài viết.</div>
            }
            else
            {
                <div class="row">
                    @using (Html.BeginForm("SendDocumentPost", "Contact", FormMethod.Post, new { @id = "form-request", @class = "", role = "form", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        @Html.HiddenFor(x => x.UserId)
                        <input type="hidden" name="ContactType" value="bai-viet-hoc-thuat" />
                        
                        <div class="col-md-24">
                            <div class="alert alert-success" style="display:none">
                                Bài viết đã được gửi
                            </div>
                            <div class="alert alert-danger" style="display:none">
                                Vui lòng điền đầy đủ nội dung trong form
                            </div>
                        </div>
                        <div class="form-horizontal col-md-16">
                            <div class="form-group">
                                <label class="col-md-6">Họ và Tên (*)</label>
                                <div class="col-md-18">
                                    @Html.TextBoxFor(x => x.Name, new { @class="form-control", placeholder="Họ và tên" })
                                    @Html.ValidationMessageFor(x => x.Name)
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-6">Email (*)</label>
                                <div class="col-md-18">
                                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control", placeholder = "Email" })
                                    @Html.ValidationMessageFor(x => x.Email)
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-6">Điện thoại</label>
                                <div class="col-md-18">
                                    @Html.TextBoxFor(x => x.Phone, new { @class = "form-control", placeholder = "Điện thoại" })
                                    @Html.ValidationMessageFor(x => x.Phone)
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-6">Tiêu đề (*)</label>
                                <div class="col-md-18">
                                    @Html.TextBoxFor(x => x.Subject, new { @class = "form-control", placeholder = "Tiêu đề" })
                                    @Html.ValidationMessageFor(x => x.Subject)
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-6">Tác giả</label>
                                <div class="col-md-18">
                                    @Html.TextBoxFor(x => x.Author, new { @class = "form-control", placeholder = "Tác giả" })
                                    @Html.ValidationMessageFor(x => x.Author)
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-6">Nơi đăng</label>
                                <div class="col-md-18">
                                    @Html.TextBoxFor(x => x.Journal, new { @class = "form-control", placeholder = "Nơi đăng bài viết" })
                                    @Html.ValidationMessageFor(x => x.Journal)
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-6">Năm đăng</label>
                                <div class="col-md-18">
                                    @Html.TextBoxFor(x => x.Year, new { @class = "form-control", placeholder = "Năm đăng bài viết" })
                                    @Html.ValidationMessageFor(x => x.Year)
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-6">Đính kèm</label>
                                <div class="col-md-18">
                                    @Html.TextBoxFor(x => x.Attachment, new { @type="file", @class = "form-control", accept = ".pdf" })
                                    @Html.ValidationMessageFor(x => x.Attachment)
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-6">Nội dung</label>
                                <div class="col-md-18">
                                    @Html.TextAreaFor(x => x.Message, new { @class = "form-control", placeholder = "Nội dung bài viết" })
                                    @Html.ValidationMessageFor(x => x.Message)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-18 col-md-offset-6">
                                    <button type="submit" class="btn btn-warning btn-submit">Gửi <i class="fa fa-send"></i></button>
                                </div>
                            </div>

                        </div>
                        <div class="col-md-8"></div>
                    }
                </div>
            }
            
        </section>
    </article>
    <section class="col-md-5">
        @Html.Partial("~/Views/Sidebar/SidebarPost.cshtml")
    </section>
</div>
@section head {
    <link rel="stylesheet" href="~/Scripts/plugins/trumbowyg/ui/trumbowyg.min.css">
}

@section scripts {
    <script src="~/Scripts/plugins/trumbowyg/trumbowyg.min.js"></script>
    <script>
        $('#Message').trumbowyg({
            btns: ['undo', 'redo', 'formatting', 'btnGrp-design', 'btnGrp-lists', 'btnGrp-justify', 'removeformat', 'fullscreen'],
            autogrow: true
        });

        @if (TempData.SafeGet("status") == "success")
        {
            @:$('#form-request .alert-success').show();
        }
        //$("#form-request").validate({
        //    invalidHandler: function (e, validator) {
        //        if (validator.errorList.length) {
        //            $('#form-request .alert-danger').show();
        //        }
        //    },
        //    submitHandler: function (form) {

        //        var subject = $('#contactSubject').val();
        //        var name = $('#contactName').val();
        //        var email = $('#contactEmail').val();
        //        var phone = $('#contactPhone').val();
        //        var message = $('#contactMessage').val();
        //        var author = $('#contactAuthor').val();
        //        var journal = $('#contactJournal').val();
        //        var year = $('#contactYear').val();

        //        var data = {
        //            name: name,
        //            email: email,
        //            phone: phone,
        //            subject: subject,
        //            message: message,
        //            type: 'bai-viet-hoc-thuat',
        //            author: author,
        //            journal: journal,
        //            year: year
        //        };
        //        $.ajax({
        //            url: "/Contact/SendDocumentPost",
        //            type: "POST",
        //            data: data,
        //            success: function (data) {
        //                if (data.status == "success") {
        //                    form.reset();
        //                    $('#form-request .alert-success').show();
        //                }
        //            }
        //        });
        //    }
        //});
    </script>
}

TVG.WebClient/Views/Contact/SendQuestion.cshtml
@{
    ViewBag.Title = "TheGioiLuat.vn - Gửi câu hỏi";

    var breadcrumb = new List<BreadcrumbViewModel>();
    breadcrumb.Add(new BreadcrumbViewModel { Text = "Gửi yêu cầu" });
}
@Html.Partial("Breadcrumb", breadcrumb)
<div class="row">
    <article class="col-md-19">
        <header>
            <h1>Gửi câu hỏi</h1>
        </header>
        <section>
            <div class="row">
                <form id="form-request">
                    <div class="col-md-24">
                        <div class="alert alert-success" style="display:none">
                            Câu hỏi đã được gửi
                        </div>
                        <div class="alert alert-danger" style="display:none">
                            Vui lòng điền đầy đủ nội dung trong form
                        </div>
                    </div>
                    <div class="form-horizontal col-md-16">
                        <div class="form-group">
                            <label class="col-md-6">Họ và Tên (*)</label>
                            <div class="col-md-18">
                                <input type="text" class="form-control required" required id="contactName" placeholder="Họ và Tên" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-6">Email (*)</label>
                            <div class="col-md-18">
                                <input type="text" class="form-control required" required id="contactEmail" placeholder="Email" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-6">Điện thoại (*)</label>
                            <div class="col-md-18">
                                <input type="text" class="form-control required" required id="contactPhone" placeholder="Điện thoại" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-6">Tiêu đề (*)</label>
                            <div class="col-md-18">
                                <input type="text" class="form-control required" required id="contactSubject" placeholder="Tiêu đề" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-6">Yêu cầu</label>
                            <div class="col-md-18">
                                <textarea class="form-control required" rows="10" id="contactMessage" required placeholder="Nội dung câu hỏi"></textarea>
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-md-18 col-md-offset-6">
                                <button type="submit" class="btn btn-warning btn-submit">Gửi <i class="fa fa-send"></i></button>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-8"></div>
                </form>
            </div>
        </section>
    </article>
    <section class="col-md-5">
        @Html.Partial("~/Views/Sidebar/SidebarPost.cshtml")
    </section>
</div>
@section scripts {
    <script>
        $("#form-request").validate({
            invalidHandler: function (e, validator) {
                if (validator.errorList.length) {
                    $('#form-request .alert-danger').show();
                }
            },
            submitHandler: function (form) {
                
                var subject = $('#contactSubject').val();
                var name = $('#contactName').val();
                var email = $('#contactEmail').val();
                var phone = $('#contactPhone').val();
                var message = $('#contactMessage').val();

                var data = {
                    name: name,
                    email: email,
                    phone: phone,
                    subject: subject,
                    message: message,
                    type: 'hoi-dap'
                };
                $.ajax({
                    url: "/Contact/SendQuestion",
                    type: "POST",
                    data: data,
                    success: function (data) {
                        if (data.status == "success") {
                            form.reset();
                            $('#form-request .alert-success').show();
                        }
                    }
                });
            }
        });
    </script>    
}